oa3_spec: src/main/resources/swagger/api-docs.json
name: opex_api-external-api
location: West Europe
timespan: 30m # Default, a number or a timespan https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/timespan
evaluation_frequency: 10
evaluation_time_window: 30
event_occurrences: 4 # After 5*4=20 min
data_source: /subscriptions/813119d7-0943-46ed-8ebe-cebe24f9106c/resourceGroups/selc-p-vnet-rg/providers/Microsoft.Network/applicationGateways/selc-p-app-gw
action_groups:
  - /subscriptions/813119d7-0943-46ed-8ebe-cebe24f9106c/resourceGroups/selc-p-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  # - /subscriptions/813119d7-0943-46ed-8ebe-cebe24f9106c/resourceGroups/selc-p-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
overrides:
  hosts: # Use these hosts instead of those inside the OpenApi spec
    - api.selfcare.pagopa.it
  endpoints:
    /institutions:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 2 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /institutions/{institutionId}/contract:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 1 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /institutions/{institutionId}/products:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 2 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /institutions/{institutionId}/users:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 2.5 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /onboarding:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 3 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /onboarding/{externalInstitutionId}:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 3 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /onboarding/{externalInstitutionId}/products/{productId}:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 5.5 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /onboarding/pda/{injectionInstitutionType}:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 2 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /pn-pg/institutions/add:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 1 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /products/{productId}:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 2.5 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /users:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 2 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 
    /users/{id}/onboarded-product:
      availability_threshold: 0.95 # Default: 99%
      availability_evaluation_frequency: 30 # Default: 10
      availability_evaluation_time_window: 50 # Default: 20
      availability_event_occurrences: 3 # Default: 1
      response_time_threshold: 1 # Default: 1
      response_time_evaluation_frequency: 10 # Default: 10
      response_time_evaluation_time_window: 30 # Default: 20
      response_time_event_occurrences: 30 # Default: 